### ISSUE TITLE
Tactical Store: Version abstraction

### ISSUE THREAD

**Issue by alxhub** [angular/tactical#9]
Implement a Version type with any required methods for making comparisons.

**Comment by ttowncompiled** [comment]
```typescript
interface Version {
  __generation__: Number;
  __version__: Number;
  __subversion__: Number;
  same(other: Version): boolean;
}
```
Generation is a count of how many times the object has been deleted and then later remade.

Version is a count of how many times the object has undergone structural changes _(not deletions)_ &mdash; in its current generation.

Subversion is a count of how many times the object has undergone property changes &mdash; in its current version.

same compares two Versions and returns true if both Versions are the same; otherwise, returns false.

**Comment by ttowncompiled** [comment]
Blocked on #21

**Comment by ttowncompiled** [comment]
See #23
